<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\User;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    /**
     * @return Project[]
     */
    public function findAllProjectsByUser(User $user)
    {
        return $this->createQueryBuilder('p')
            //->leftJoin('p.tasks', 't')
            ->andWhere('p.user = :user')
            ->setParameter('user', $user)
            ->orderBy('p.createdAt', 'DESC')
            ->getQuery()
            ->execute();
    }

    public function createAlphabeticalQueryBuilder(User $user)
    {
        return $this->createQueryBuilder('p')
            ->andWhere('p.user = :user')
            ->setParameter('user', $user)
            ->orderBy('p.createdAt', 'DESC');
    }

    public function getProjectsAndTasks(User $user){

        $conn = $this->getEntityManager()
            ->getConnection();
        $sql = '
                SELECT
                    p.project_name,
                    (
                        SELECT
                            COUNT(*)
                        FROM
                            task t
                        WHERE
                            t.project_id = p.id
                        AND t.is_done = 0    
                    ) count_tasks
                FROM
                    project p
                WHERE
                    p.user_id = :user
              ';
        $stmt = $conn->prepare($sql);
        $stmt->execute(array('user'=>$user->getId()));
        $result = $stmt->fetchAll();

        return $result;
    }
}
