<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\User;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    public function findByTerms(array $terms, User $user)
    {
        $queryBuilder = $this->createQueryBuilder('p');

        foreach ($terms as $key => $term) {
            $queryBuilder
                ->orWhere('p.taskName LIKE :t_'.$key)
                ->setParameter('t_'.$key, '%'.$term.'%')
            ;
        }
        $queryBuilder->andWhere('p.user = :u AND p.isDone = :done')
            ->setParameter('u', $user)
            ->setParameter('done', 0);

        return $queryBuilder
            ->orderBy('p.createdAt', 'DESC')
            ->getQuery()
            //->getSql();
            ->getResult();
    }

    public function findProjectName($id)
    {
        return $this->createQueryBuilder('t')
            ->select(['p.id','p.projectName'])
            ->innerJoin('t.project', 'p')
            ->where('t.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getSingleResult();
            //->execute();
    }
}